server:
  port: 81
#eureka:
#  client:
#    instance-id: consumer
##    register-with-eureka: false
#    service-url:
#      defaultZone: http://eurekaserver8090.com:8090/eureka/,http://eurekaserver8091.com:8091/eureka/

spring:
  application:
    name: consumer

eureka:
  instance:
    prefer-ip-address: true
    instance-id: 192.168.1.100:81
  client:
    service-url:
      defaultZone: http://eurekaserver8090.com:8090/eureka/,http://eurekaserver8091.com:8091/eureka/

feign:
  hystrix:
    enabled: true
