package com.zy.springcloudapi.entites;


public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column javas1..user.id
     *
     * @mbg.generated Sun Aug 25 18:44:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column javas1..user.name
     *
     * @mbg.generated Sun Aug 25 18:44:13 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column javas1..user.dbSource
     *
     * @mbg.generated Sun Aug 25 18:44:13 CST 2019
     */
    private String dbsource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column javas1..user.id
     *
     * @return the value of javas1..user.id
     *
     * @mbg.generated Sun Aug 25 18:44:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column javas1..user.id
     *
     * @param id the value for javas1..user.id
     *
     * @mbg.generated Sun Aug 25 18:44:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column javas1..user.name
     *
     * @return the value of javas1..user.name
     *
     * @mbg.generated Sun Aug 25 18:44:13 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column javas1..user.name
     *
     * @param name the value for javas1..user.name
     *
     * @mbg.generated Sun Aug 25 18:44:13 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column javas1..user.dbSource
     *
     * @return the value of javas1..user.dbSource
     *
     * @mbg.generated Sun Aug 25 18:44:13 CST 2019
     */
    public String getDbsource() {
        return dbsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column javas1..user.dbSource
     *
     * @param dbsource the value for javas1..user.dbSource
     *
     * @mbg.generated Sun Aug 25 18:44:13 CST 2019
     */
    public void setDbsource(String dbsource) {
        this.dbsource = dbsource;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", dbsource='" + dbsource + '\'' +
                '}';
    }
}