package com.zy.springcloudprovider8081.dao;


import java.util.List;

import com.zy.springcloudapi.entites.User;
import com.zy.springcloudapi.entites.UserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.stereotype.Component;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table javas1..user
     *
     * @mbg.generated Sun Aug 25 18:43:55 CST 2019
     */
    int updateByPrimaryKey(User record);
}